CREATE TABLE "Users" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR(255) UNIQUE NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Posts" (
    "id" SERIAL PRIMARY KEY,
    "content" TEXT NOT NULL,
    "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Follows" (
    "followerId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "followingId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    PRIMARY KEY ("followerId", "followingId"),
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Likes" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "postId" INTEGER NOT NULL REFERENCES "Posts" ("id") ON DELETE CASCADE,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Comments" (
    "id" SERIAL PRIMARY KEY,
    "content" TEXT NOT NULL,
    "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "postId" INTEGER NOT NULL REFERENCES "Posts" ("id") ON DELETE CASCADE,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
``
